# Generated by Django 3.0.6 on 2020-07-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_date', models.DateField()),
                ('post_text', models.CharField(max_length=300)),
                ('post_image', models.ImageField(upload_to='post_images/')),
            ],
        ),
    ]
